[RELENG-219] Should be able to only build a subset of the product with mg

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -173,19 +173,19 @@ function gen_config() {
 TIMESTAMP=$(TZ=UTC date "+%Y%m%dT%H%M%SZ")
 
 SMARTLOGIN_BRANCH=$BRANCH
-SMARTLOGIN_SHA=$(cd build/smartlogin ; git log --pretty=format:'%h' -1 )
+SMARTLOGIN_SHA=$((cd build/smartlogin 2>&1 > /dev/null && git log --pretty=format:'%h' -1 ) || echo "")
 
 AGENTS_BRANCH=$BRANCH
-AGENTS_SHA=$(cd build/agents ; git log --pretty=format:'%h' -1 )
+AGENTS_SHA=$((cd build/agents 2>&1 > /dev/null && git log --pretty=format:'%h' -1 ) || echo "")
 
 CA_BRANCH=$BRANCH
-CA_SHA=$(cd build/ca ; git log --pretty=format:'%h' -1 )
+CA_SHA=$((cd build/ca 2>&1 > /dev/null && git log --pretty=format:'%h' -1 ) || echo "")
 
 AGENTSSHAR_BRANCH=$BRANCH
-AGENTSSHAR_SHA=$(cd build/agents-installer ; git log --pretty=format:'%h' -1 )
+AGENTSSHAR_SHA=$((cd build/agents-installer 2>&1 > /dev/null && git log --pretty=format:'%h' -1 ) || echo "")
 
 USBHEADNODE_BRANCH=$BRANCH
-USBHEADNODE_SHA=$(cd build/usb-headnode ; git log --pretty=format:'%h' -1 )
+USBHEADNODE_SHA=$((cd build/usb-headnode 2>&1 > /dev/null && git log --pretty=format:'%h' -1 ) || echo "")
 
 BUILD_PLATFORM=$BUILD_PLATFORM
 EOF
@@ -201,7 +201,7 @@ for zone in $ZONES; do
     capzone=$(echo $zone | tr [:lower:] [:upper:] | tr - _)
     cat <<EOF >>config.mk
 ${capzone}_BRANCH=$BRANCH
-${capzone}_SHA=$(cd build/$zone ; git log --pretty=format:'%h' -1 )
+${capzone}_SHA=$((cd build/$zone 2>&1 > /dev/null && git log --pretty=format:'%h' -1 ) || echo "")
 EOF
 
 done
@@ -219,15 +219,16 @@ function print_help() {
     echo "component source repositories."
     echo ""
     echo "Usage:"
-    echo "  ./configure [ -b BRANCH ] [ -n ] [ -r TARGET [-f] ]"
+    echo "  ./configure [ -b BRANCH ] [ -n ] [ -r REPO [-f] ] [ -s TARGET ]"
     echo ""
     echo "Options:"
     echo "  -h           Print this help and exit."
     echo "  -b BRANCH    Branch to checkout. Defaults to 'master'."
     echo "               Note that this is for *all* core repositories."
     echo "  -n           Do not build platform (only applicable on SmartOS)"
-    echo "  -r TARGET    Reconfigure build. Remove build artifacts, checkout to SHA in config.mk or HEAD"
+    echo "  -r REPO      Reconfigure build. Remove build artifacts, checkout to SHA in config.mk or HEAD"
     echo "  -f           Force reconfig (clean and rebuild)"
+    echo "  -s TARGET    Only checkout repos required to build TARGET" 
     exit 0
 }
 
@@ -237,19 +238,20 @@ function print_help() {
 
 trap 'errexit $? $LINENO' EXIT
 
-while getopts ":b:hunr:f" opt; do
+while getopts ":b:hunr:fs:" opt; do
     case $opt in
         b) BRANCH=$OPTARG;;
         h) print_help ;;
         n) BUILD_PLATFORM='false' ;;
         r) RECONFIG='true' ; RECONF_REPO=${OPTARG} ;;
+        s) SOLE='true' ; SOLE_REPO=${OPTARG} ;;
         f) FORCE_RECONFIG='true' ;;
         ?) fatal "unknown option: $opt" ;;
     esac
     shift $((OPTIND-1))
 done
 
-if [[ $RECONFIG == 'true' && -z $RECONF_REPO ]]; then
+if [[ $RECONFIG == 'true' && -z $RECONF_REPO || $SOLE == 'true' && -z $SOLE_REPO ]]; then
   print_help
   exit 1
 fi
@@ -259,25 +261,46 @@ fi
 # the clean targets.
 touch config.mk
 
-# TODO: not sure about allow no arg to '-r'. Doesn't that screw up './configure -r -n'?
-if [[ -n $RECONF_REPO ]]; then
-  if [[ $(echo $ZONES | grep $RECONF_REPO) ]]; then
-    get_zone_repo $RECONF_REPO $BRANCH
-  else
-    targ=$(cat repos.json | json $RECONF_REPO | json target)
-    if [[ -n $targ ]]; then
-      RECONF_REPO=$targ
+if [[ $SOLE != 'true' ]]; then
+  # TODO: not sure about allow no arg to '-r'. Doesn't that screw up './configure -r -n'?
+  if [[ -n $RECONF_REPO ]]; then
+    if [[ $(echo $ZONES | grep $RECONF_REPO) ]]; then
+      get_zone_repo $RECONF_REPO $BRANCH
+    else
+      targ=$(cat repos.json | json $RECONF_REPO | json target)
+      if [[ -n $targ ]]; then
+        RECONF_REPO=$targ
+      fi
+      get_$RECONF_REPO $BRANCH
     fi
-    get_$RECONF_REPO $BRANCH
+  else
+    get_smartlogin $BRANCH
+    get_ca $BRANCH
+    get_agents $BRANCH
+    get_agentsshar $BRANCH
+    get_usbheadnode $BRANCH
+    get_illumoslive $BRANCH
+    get_zones $BRANCH
   fi
 else
-  get_smartlogin $BRANCH
-  get_ca $BRANCH
-  get_agents $BRANCH
-  get_agentsshar $BRANCH
-  get_usbheadnode $BRANCH
-  get_illumoslive $BRANCH
-  get_zones $BRANCH
+  if [[ $SOLE_REPO == 'usb-headnode' ]]; then
+    get_smartlogin $BRANCH
+    get_ca $BRANCH
+    get_agents $BRANCH
+    get_agentsshar $BRANCH
+    get_usbheadnode $BRANCH
+    get_illumoslive $BRANCH
+    get_zones $BRANCH
+  elif [[ $SOLE_REPO == 'agents-installer' ]]; then
+    get_agentsshar $BRANCH
+    get_agents $BRANCH
+    get_smartlogin $BRANCH
+    get_ca $BRANCH
+  elif [[ $SOLE_REPO == 'illumos-live' ]]; then
+    get_illumoslive $BRANCH
+  else
+    get_repo $BRANCH $SOLE_REPO $SOLE_REPO
+  fi
 fi
 
 gen_config
