RELENG-353 rip out unused RELENG-293 build-component-in-new-zone

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -27,8 +27,8 @@ TRY_BRANCH=
 
 # These two are used for tracking which targets will be built in a
 # provisioned zone (separate from the current zone).
-USEZONE=
-NOUSEZONE=
+# USEZONE=
+# NOUSEZONE=
 
 ROOT=$(pwd)
 MG_CACHE_DIR=${ROOT}/cache
@@ -232,31 +232,31 @@ function preload_bits() {
 }
 
 
-#
-# The requested target may use the new functionality to build it inside of an
-# SDC zone. We check that here and note it for later use. We need to see whether
-# use zone is set for the specified branch.
-#
-# Based on targets.json, we have three specific states. Something is entirely in
-# the old world, in which case, neither USEZONE or NOUSEZONE get set. If the
-# usezone value is there, then we need to check which it is so we can properly
-# emit the right Makefile target snippet.
-#
-function check_usezone() {
-	local zone use
-	local target=$1
+# #
+# # The requested target may use the new functionality to build it inside of an
+# # SDC zone. We check that here and note it for later use. We need to see whether
+# # use zone is set for the specified branch.
+# #
+# # Based on targets.json, we have three specific states. Something is entirely in
+# # the old world, in which case, neither USEZONE or NOUSEZONE get set. If the
+# # usezone value is there, then we need to check which it is so we can properly
+# # emit the right Makefile target snippet.
+# #
+# function check_usezone() {
+# 	local zone use
+# 	local target=$1
 
-	zone=$($JSON $target < targets.json)
-	[[ $? -eq 0 ]] || fatal "failed to read targets.json"
-	use=$(echo $zone | $JSON usezone)
-	if [[ -n "$use" ]]; then
-		if [[ "$use" == "true" ]]; then
-			USEZONE="$target $USEZONE"
-		else
-			NOUSEZONE="$target $NOUSEZONE"
-		fi
-	fi
-}
+# 	zone=$($JSON $target < targets.json)
+# 	[[ $? -eq 0 ]] || fatal "failed to read targets.json"
+# 	use=$(echo $zone | $JSON usezone)
+# 	if [[ -n "$use" ]]; then
+# 		if [[ "$use" == "true" ]]; then
+# 			USEZONE="$target $USEZONE"
+# 		else
+# 			NOUSEZONE="$target $NOUSEZONE"
+# 		fi
+# 	fi
+# }
 
 # Clone/update the given git repo in the repo cache.
 # Usage:
@@ -376,15 +376,15 @@ EOF
       fi
   done
 
-  touch ${ROOT}/bits/config.targ.mk
-  for targ in $USEZONE; do
-      output="\$($(echo $targ | tr [:lower:] [:upper:])_BITS): config_${targ}_new"
-      echo $output >> ${ROOT}/bits/config.targ.mk
-  done
-  for targ in $NOUSEZONE; do
-      output="\$($(echo $targ | tr [:lower:] [:upper:])_BITS): config_${targ}_old"
-      echo $output >> ${ROOT}/bits/config.targ.mk
-  done
+  # touch ${ROOT}/bits/config.targ.mk
+  # for targ in $USEZONE; do
+  #     output="\$($(echo $targ | tr [:lower:] [:upper:])_BITS): config_${targ}_new"
+  #     echo $output >> ${ROOT}/bits/config.targ.mk
+  # done
+  # for targ in $NOUSEZONE; do
+  #     output="\$($(echo $targ | tr [:lower:] [:upper:])_BITS): config_${targ}_old"
+  #     echo $output >> ${ROOT}/bits/config.targ.mk
+  # done
 }
 
 
@@ -558,7 +558,7 @@ fi
 # Else we are doing a full configure for a fresh build. Start fresh:
 mkdir -p bits
 touch bits/config.mk
-touch bits/config.targ.mk
+# touch bits/config.targ.mk
 make distclean
 
 
@@ -568,7 +568,7 @@ if [[ ! -z "$TARGET" ]]; then
         preload_bits "platform" "$BRANCH" "$TRY_BRANCH"
         TARGETS=$(${MG_NODE} -e 'fs=require("fs"); c=fs.readFileSync("targets.json"); console.log(Object.keys(JSON.parse(c)).join("\n"))' | grep -v '^platform')
         for targ in $TARGETS; do
-            check_usezone $targ
+            # check_usezone $targ
             get_target_repos $targ
             for dep in `cat targets.json | $JSON $targ.deps | $JSON -a`; do
                 preload_bits $dep "$BRANCH" "$TRY_BRANCH"
@@ -580,7 +580,7 @@ if [[ ! -z "$TARGET" ]]; then
         if [[ -z "$(cat targets.json | $JSON $TARGET)" ]]; then
             fatal "Unknown target: $TARGET"
         fi
-        check_usezone $TARGET
+        # check_usezone $TARGET
         get_target_repos $TARGET
         for dep in `cat targets.json | $JSON $TARGET.deps | $JSON -a`; do
             preload_bits $dep "$BRANCH" "$TRY_BRANCH"
@@ -589,7 +589,7 @@ if [[ ! -z "$TARGET" ]]; then
 else
     TARGETS=$(${MG_NODE} -e 'fs=require("fs"); c=fs.readFileSync("targets.json"); console.log(Object.keys(JSON.parse(c)).join("\n"))')
     for targ in $TARGETS; do
-        check_usezone $targ
+        # check_usezone $targ
         get_target_repos $targ
     done
 fi
