TOOLS-1986 MG's ./tools/ls-missing-release-builds will falsely report missing builds if mls env isn't properly setup Reviewed by: Marsell Kukuljevic <marsell@joyent.com> Approved by: Marsell Kukuljevic <marsell@joyent.com>

diff --git a/tools/ls-missing-release-builds b/tools/ls-missing-release-builds
--- a/tools/ls-missing-release-builds
+++ b/tools/ls-missing-release-builds
@@ -71,6 +71,10 @@ if [[ -z "$targets" ]]; then
         | grep -v '^headnode-joyent-debug ')
 fi
 
+# Ensure mls is setup properly at all.
+mls /Joyent_Dev/public/builds >/dev/null \
+    || fatal "cannot list /Joyent_Dev/public/builds"
+
 echo "$targets" | while read target public; do
     if [[ "$public" == "true" ]]; then
         latest_mpath=/Joyent_Dev/public/builds/$target/$release-latest
